name: Build latest Docker images

on:
  push:
    branches:
      - main

concurrency:
  group: build-latest-docker-images
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  build-latest-docker-image:
    name: Build and push latest Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Login to GitHub Container Registry
        # v2.2.0
        uses: docker/login-action@5139682d94efc37792e6b54386b5b470a68a4737
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: bash .ci-scripts/release/build-latest-docker-images.bash
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.

  prune-untagged-images:
    needs:
      - build-latest-docker-image

    name: Prune untagged images
    runs-on: ubuntu-latest
    steps:
      - name: Prune
        # v3.0.1
        uses: snok/container-retention-policy@3b0972b2276b171b212f8c4efbca59ebba26eceb
        with:
          account: ponylang
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: changelog-tool
          tag-selection: untagged
          cut-off: 1d
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.
