name: Release

on:
  push:
    tags:
      - \d+.\d+.\d+

jobs:
  # validation to assure that we should in fact continue with the release should
  # be done here. the primary reason for this step is to verify that the release
  # was started correctly by pushing a `release-X.Y.Z` tag rather than `X.Y.Z`.
  pre-artefact-creation:
    name: Tasks to run before artefact creation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: "main"
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Validate CHANGELOG
        uses: ponylang/release-bot-action@0.6.1
        with:
          entrypoint: pre-artefact-changelog-check

  x86-64-unknown-linux-release:
    name: Build and upload x86-64-unknown-linux-release to Cloudsmith
    runs-on: ubuntu-latest
    needs:
      - pre-artefact-creation
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder:release
    steps:
      - uses: actions/checkout@v1
      - name: Build and upload
        run: bash .ci-scripts/release/x86-64-unknown-linux-release.bash
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

  x86-64-apple-darwin-release:
    name: Build and upload x86-64-apple-darwin-release to Cloudsmith
    runs-on: macos-latest
    needs:
      - pre-artefact-creation
    steps:
      - uses: actions/checkout@v1
      - name: Install pony tools
        run: bash .ci-scripts/install-macOS-tools.bash
      - name: brew install dependencies
        run: brew install coreutils
      - name: pip install dependencies
        run: pip3 install --upgrade cloudsmith-cli
      - name: Build and upload
        run: bash .ci-scripts/release/x86-64-apple-darwin-release.bash
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

  build-release-docker-images:
    name: Build and push release Docker images
    runs-on: ubuntu-latest
    needs:
      - pre-artefact-creation
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash .ci-scripts/release/build-docker-images-on-release.bash

  trigger-release-announcement:
    needs:
      - x86-64-unknown-linux-release
      - x86-64-apple-darwin-release
      - build-release-docker-images

    name: Trigger release announcement
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: "main"
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Trigger
        uses: ponylang/release-bot-action@0.6.1
        with:
          entrypoint: trigger-release-announcement
        env:
          GIT_USER_NAME: "Ponylang Main Bot"
          GIT_USER_EMAIL: "ponylang.main@gmail.com"

  send-release-event:
    needs:
      - x86-64-unknown-linux-release
      - x86-64-apple-darwin-release
      - build-release-docker-images
    name: Send release event
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['ponylang/shared-docker']
    steps:
      - name: Send
        uses: ponylang-main/repository-dispatch@ce5485de42c9b2622d2ed064be479e8ed65e76f4
        with:
          token: ${{ secrets.PONYLANG_MAIN_API_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: changelog-tool-released
          client-payload: '{}'
