name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

concurrency: release

permissions:
  packages: write
  contents: write

jobs:
  # validation to assure that we should in fact continue with the release should
  # be done here. the primary reason for this step is to verify that the release
  # was started correctly by pushing a `release-X.Y.Z` tag rather than `X.Y.Z`.
  pre-artefact-creation:
    name: Tasks to run before artefact creation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4.1.1
        with:
          ref: "main"
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Validate CHANGELOG
        uses: docker://ghcr.io/ponylang/release-bot-action:0.6.3
        with:
          entrypoint: pre-artefact-changelog-check

  # Currently, GitHub actions supplied by GH like checkout and cache do not work
  # in musl libc environments on arm64. We can work around this by running
  # those actions on the host and then "manually" doing our work that would
  # normally be done "in the musl container" by starting the container ourselves
  # for various steps by invoking docker directly.
  #
  # This is not in line with our standard pattern of "just do it all in the
  # container" but is required to work around the GitHub actions limitation
  # documented above.
  arm64-unknown-linux-release:
    name: Build and upload arm64-unknown-linux-release to Cloudsmith
    runs-on: ubuntu-24.04-arm
    needs:
      - pre-artefact-creation
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Pull Docker image
        run: docker pull ghcr.io/ponylang/shared-docker-ci-standard-builder:release
      - name: Build and upload
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/root/project \
            -w /root/project \
            -e CLOUDSMITH_API_KEY=${{ secrets.CLOUDSMITH_API_KEY }} \
            -e GITHUB_REPOSITORY=${{ github.repository }} \
            ghcr.io/ponylang/shared-docker-ci-standard-builder:release \
            bash .ci-scripts/release/arm64-unknown-linux-release.bash

  x86-64-unknown-linux-release:
    name: Build and upload x86-64-unknown-linux-release to Cloudsmith
    runs-on: ubuntu-latest
    needs:
      - pre-artefact-creation
    container:
      image: ghcr.io/ponylang/shared-docker-ci-standard-builder:release
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Build and upload
        run: bash .ci-scripts/release/x86-64-unknown-linux-release.bash
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

  build-release-docker-images:
    name: Build and push release Docker images
    runs-on: ubuntu-latest
    needs:
      - pre-artefact-creation
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Login to GitHub Container Registry
        # v2.2.0
        uses: docker/login-action@5139682d94efc37792e6b54386b5b470a68a4737
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: bash .ci-scripts/release/build-docker-images-on-release.bash

  trigger-release-announcement:
    needs:
      - arm64-unknown-linux-release
      - x86-64-unknown-linux-release
      - build-release-docker-images

    name: Trigger release announcement
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: "main"
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Trigger
        uses: docker://ghcr.io/ponylang/release-bot-action:0.6.3
        with:
          entrypoint: trigger-release-announcement
        env:
          GIT_USER_NAME: "Ponylang Main Bot"
          GIT_USER_EMAIL: "ponylang.main@gmail.com"

  send-release-event:
    needs:
      - x86-64-unknown-linux-release
      - build-release-docker-images
    name: Send release event
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: ['ponylang/shared-docker']
    steps:
      - name: Send
        # v2.1.1
        uses: peter-evans/repository-dispatch@8324ecf35877f9b02961dd5aaf43ed7be7db9373
        with:
          token: ${{ secrets.PONYLANG_MAIN_API_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: changelog-tool-released
          client-payload: '{}'
